backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      # HOME PAGE
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          # Main cover fields
          - {
              label: Main cover,
              name: mainCover,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # Kind of coffee
          - {
              label: Type of coffee,
              name: coffeeType,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
                {
                  label: Coffee,
                  name: coffees,
                  widget: list,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: "Alt image", name: altImage, widget: string},
                    {label: Heading, name: heading, widget: string},
                    {label: Subheading, name: subheading, widget: text},
                    {label: Call to action, name: cta, widget: string},
                    {label: Link, name: link, widget: string},
                  ],
                },
              ],
            }
          # Moka secrets
          - {
              label: Moka secrets,
              name: mokaSecrets,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
              {
                label: Secrets,
                name: secrets,
                widget: list,
                fields: [
                  {label: Image, name: image, widget: image},
                  {label: "Alt image", name: altImage, widget: string},
                  {label: Title, name: title, widget: string},
                  {label: Description, name: description, widget: text},
                ],
              },
            }

      # HISTORY PAGE
      - file: "src/pages/history/index.md"
        label: "History page"
        name: "history"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "history-page"}
          - {label: Title, name: title, widget: string}
          - {
              label: Paragraphs,
              name: paragraphs,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label:Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block]},
              ],
            }
          - {label: History title, name: historyTitle, widget: string}
          - {
              label: History steps,
              name: historySteps,
              widget: list,
              fields: [
                {label: Image, name: image, widget: image, default: /img/service-placeholder.png},
                {label: "Alt image", name: alt, widget: string},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
              ],
            }
          - {label: "Banner", name: bannerName, widget: string}

      # COFFEE PAGES
      - file: "src/pages/good/index.md"
        label: "La buona"
        name: "good"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "coffee-page"}
          - {label: Cover, name: cover, widget: image}
          - {label: "Alt cover", name: altCover: widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Alt image", name: altImage: widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Short description, name: shortDesc, widget: string}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block]}
          - {label: "Banner", name: bannerName, widget: string}

      - file: "src/pages/excellent/index.md"
        label: "La Migliore"
        name: "excellent"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "coffee-page"}
          - {label: Cover, name: cover, widget: image}
          - {label: "Alt cover", name: altCover: widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Alt image", name: altImage: widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Short description, name: shortDesc, widget: string}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block]}
          - {label: "Banner", name: bannerName, widget: string}

      - file: "src/pages/best/index.md"
        label: "La ancora meglio"
        name: "best"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "coffee-page"}
          - {label: Cover, name: cover, widget: image}
          - {label: "Alt cover", name: altCover: widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Alt image", name: altImage: widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Short description, name: shortDesc, widget: string}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block]}
          - {label: "Banner", name: bannerName, widget: string}

      # BLENDS PAGE
      - file: "src/pages/blends/index.md"
        label: "Blends page"
        name: "blends"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "blends-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Alt image, name: altImage, widget: string}
          - {label: "Banner", name: bannerName, widget: string}
          - {
              label: Blend selections,
              name: blendSelection,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block]},
                {label: Image, name: image, widget: image},
                {label: Alt image, name: altImage, widget: string},
              ],
            }
          - {label: Blend title, name: blendTitle, widget: string}
          - {
              label: Blends,
              name: blends,
              widget: list,
              fields: [
                {label: Name, name: name, widget: string},
                {label: "Visible on homepage", name: main, widget: boolean},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Origin, name: origin, widget: string},
                {label: Description, name: description, widget: string},
              ],
            }

      # BANNERS
      - file: "src/pages/banners/index.md"
        label: "Banners list"
        name: "banners"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "banners"}
          # SIGN UP BOX
          - {
              label: Sign in box,
              name: box,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Alt image, name: alt, widget: string},
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # ROWS
          - {
              label: Banners,
              name: banners,
              widget: list,
              fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image, default: "/img/placeholder.png"},
                {label: Alt image, image: alt, widget: string},
                {label: Banner title, name: title, widget: string},
                {label: Banner text, name: text, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link, name: link, widget: string},
              ],
            }
