backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          # Main cover fields
          - {
              label: Main cover,
              name: mainCover,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }

          # First sing-in row
          - {
              label: Sign in box,
              name: topSignIn,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }

          # Partners section
          - {
              label: Partners section,
              name: partnersSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }

          # School section
          - {
              label: School section,
              name: schoolSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
                {label: Bullet, name: bullet, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Subheading, name: subheading, widget: string}, {label: Call to action, name: cta, widget: markdown}, {label: Link, name: link, widget: string}]},
              ],
            }

          # Students sectioin
          - {
              label: Student section,
              name: studentsSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
                {label: Bullet, name: bullet, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Subheading, name: subheading, widget: string}, {label: Call to action, name: cta, widget: markdown}, {label: Link, name: link, widget: string}]},
              ],
            }

          # Second submission row
          - {
              label: Sign in box,
              name: bottomSignIn,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }

          # Teachers section
          - {
              label: Teachers section,
              name: teachersSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }

          # News section
          - {
              label: News section,
              name: newsSection,
              widget: object,
              fields: [
                {label: Heading news, name: heading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to , name: link, widget: string},
              ],
            }

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/students/index.md"
        label: "Students page"
        name: "students"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "students-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Students, name: students, widget: list, fields: [{label: Full name, name: fullName, widget: string}, {label: "Visible on homepage", name: main, widget: boolean}, {label: Image, name: image, widget: image, default: /img/student-img.png}, {label: "Alt image", name: altImage, widget: string}, {label: Master, name: master, widget: number, default: 2010, valueType: int, min: 2010, max: 2030}, {label: Company, name: company, widget: string}, {label: Role, name: role, widget: string},{label: Description, name: description, widget: markdown}]}
      - file: "src/pages/school/index.md"
        label: "School page"
        name: "school"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "school-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/partners/index.md"
        label: "Partners list"
        name: "partners"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "partners"}
          - {label: Partners, name: partners, widget: list, fields: [{label: Full name, name: name, widget: string}, {label: Image, name: image, widget: image, default: /img/student-img.png}, {label: "Alt image", name: altImage, widget: string}, {label: Description, name: description, widget: markdown}, {label: "Link", name: link, widget: string}, {label: "Show in home", name: main, widget: boolean}]}
      - file: "src/pages/teachers/index.md"
        label: "Teachers list"
        name: "teachers"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "teachers"}
          - {label: Teachers, name: teachers, widget: list, fields: [{label: Full name, name: fullName, widget: string}, {label: Image, name: image, widget: image, default: /img/student-img.png}, {label: "Alt image", name: altImage, widget: string}, {label: Link, name: link, widget: string}, {label: Role, name: role, widget: string}, {label: Biography, name: bio, widget: markdown}]}
