backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Redirect from", name: "redirect_from", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      # HOME PAGE
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/alumni"}
          # Main cover fields
          - {
              label: Main cover,
              name: mainCover,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: "Alt image", name: altImage, widget: string },
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string, required: false},
              ],
            }
          # Partners section
          - {
              label: Partners section,
              name: partnersSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string, required: false},
              ],
            }
          # School section
          - {
              label: School section,
              name: schoolSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: "Alt image", name: altImage, widget: string },
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string, required: false},
                {
                  label: Bullet,
                  name: bullet,
                  widget: list,
                  fields: [
                    {label: Heading, name: heading, widget: string},
                    {label: Subheading, name: subheading, widget: text, required: false},
                    {label: Call to action, name: cta, widget: string},
                    {label: Link, name: link, widget: string, required: false},
                  ],
                },
              ],
            }
          # Students section
          - {
              label: Student section,
              name: studentsSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string, required: false},
              ],
            }
          # Teachers section
          - {
              label: Teachers section,
              name: teachersSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string, required: false},
              ],
            }
          # News section
          - {
              label: News section,
              name: newsSection,
              widget: object,
              fields: [
                {label: Heading news, name: heading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to , name: link, widget: string, required: false},
              ],
            }

      # MASTER PAGE
      - file: "src/pages/master/index.md"
        label: "Master page"
        name: "master"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "master-page"}
          - {label: "Redirect from", name: "redirect_from", widget: "hidden", default: "/il-master"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Alt image", name: altImage, widget: string}
          - {
              label: Paragraphs,
              name: paragraphs,
              widget: list,
              required: false,
              fields: [
                {label: Title, name: title, widget: string},
                {label:Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
              ],
            }
          - {label: Service title, name: serviceTitle, widget: string}
          - {
              label: Services,
              name: services,
              widget: list,
              fields: [
                {label: Image, name: image, widget: image, default: /img/service-placeholder.png},
                {label: "Alt image", name: alt, widget: string},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string, required: false},
              ],
            }
          - {
              label: Scientific Committee,
              name: scientificCommittee,
              widget: object,
              required: false,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
              ],
            }
          - {
              label: People,
              name: people,
              widget: list,
              required: false,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
              ],
            }
          - {
              label: "Footer banner",
              name: footerBanner,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }

      # PROGRAM PAGE
      - file: "src/pages/programma/index.md"
        label: "Program page"
        name: "program"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "program-page"}
          - {label: "Redirect from", name: "redirect_from", widget: "hidden", default: "/struttura"}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]}
          - {label: Title paragraphs, name: titleParagraphs, widget: string}
          - {
              label: Paragraphs,
              name: paragraphs,
              widget: list,
              required: false,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
              ],
            }
          - {
              label: "Footer left banner",
              name: bannerLeft,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }
          - {
              label: "Footer right banner",
              name: bannerRight,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }

      # PROJECTS PAGE
      - file: "src/pages/projects/index.md"
        label: "Projects page"
        name: "projects"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "projects-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/projects"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Alt image, name: altImage, widget: string}
          - {label: Lab projects title, name: titleLabProjects, widget: string}
          - {
              label: Lab projects,
              name: labProjects,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
                {label: Video, name: video, widget: file, required: false},
                {label: Alt video, name: altVideo, widget: string, required: false},
                {
                  label: Gallery,
                  name: images,
                  widget: list,
                  required: false,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: Alt image, name: altImage, widget: string}
                  ],
                }
              ],
            }
          - {label: Projects title, name: titleProjects, widget: string}
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
                {label: Image, name: image, widget: image},
                {label: Alt image, name: altImage, widget: string},
              ],
            }
          - {label: Game jam title, name: titleGameJam, widget: string}
          - {
              label: Game Jam,
              name: gameJam,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
                {label: Image, name: image, widget: image},
                {label: Alt image, name: altImage, widget: string},
              ],
            }
          - {label: Projects media title, name: titleProjectsMedia, widget: string}
          - {
              label: Projects media,
              name: projectsMedia,
              hint: maximum number of 12 items,
              widget: list,
              required: false,
              fields: [
                {label: Image, name: image, widget: image, default: /img/placeholder.png, required: false},
                {label: Video, name: video, widget: file, required: false},
                {label: Alt, name: altImage, widget: string},
              ],
            }
          - {
              label: "Footer banner",
              name: footerBanner,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }

      # STUDENTS PAGE
      - file: "src/pages/students/index.md"
        label: "Students page"
        name: "students"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "students-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/alumni"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Alt image, name: altImage, widget: string}
          - {
              label: Students,
              name: students,
              widget: list,
              fields: [
                {label: Full name, name: fullName, widget: string},
                {label: Linkedin link, name: linkedin, widget: string, required: false},
                {label: "Visible on homepage", name: main, widget: boolean, required: false},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Master, name: master, widget: number, default: 2010, valueType: int, min: 2010, max: 2030},
                {label: Company, name: company, widget: string, required: false},
                {label: Company website, name: compLink, widget: string, required: false},
                {label: Quote, name: quote, widget: text, hint: 'We recommend not to exceed 240 characters'},
                {label: Games, name: games, widget: text, required: false},
              ],
            }
          - {
              label: "Footer banner",
              name: footerBanner,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }

      # PARTNERS PAGE
      - file: "src/pages/partners/index.md"
        label: "Partners list"
        name: "partners"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "partners-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/collaborazioni"}
          - {label: "Cover image", name: image, widget: image, default: /img/placeholder.png, required: false}
          - {label: "Alt image", name: altImage, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]}
          - {label: "Partners title", name: partnersTitle, widget: string}
          - {
              label: Partners,
              name: partners,
              widget: list,
              fields: [
                {label: Full name, name: name, widget: string},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]},
                {label: "Link", name: link, widget: string, required: false},
                {label: "Show in home", name: main, widget: boolean, required: false}
              ],
            }
          - {
              label: "Footer banner",
              name: footerBanner,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }
      # TEACHERS PAGE
      - file: "src/pages/teachers/index.md"
        label: "Teachers list"
        name: "teachers"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "teachers-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/docenti"}
          - {label: "Cover image", name: image, widget: image, default: /img/placeholder.png}
          - {label: "Alt image", name: altImage, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown, buttons: [bold, italic, code, link, code-block, bulleted-list]}
          - {label: "Teachers title", name: techersTitle, widget: string}
          - {
              label: Teachers,
              name: teachers,
              widget: list,
              fields: [
                {label: Full name, name: fullName, widget: string},
                {label: Image, name: image, widget: image, default: /img/student-img.png, required: false},
                {label: "Alt image", name: altImage, widget: string},
                {label: Link, name: link, widget: string, required: false},
                {label: Role, name: role, widget: string, required: false},
                {label: Biography, name: bio, widget: string, required: false}
              ],
            }
          - {
              label: "Footer banner",
              name: footerBanner,
              widget: "relation",
              collection: "pages",
              searchFields: "banners.banners.name",
              valueField: "banners.banners.name",
              displayFields: "banners.banners.name",
            }

      # BANNERS
      - file: "src/pages/banners/index.md"
        label: "Banners list"
        name: "banners"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "banners"}
          # SIGN UP BOX
          - {
              label: Sign in box,
              name: box,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: Alt image, name: alt, widget: string, required: false},
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text, required: false},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # ROWS
          - {
              label: Banners,
              name: banners,
              widget: list,
              fields: [
                {label: Name, name: name, widget: string, required: true},
                {label: Image, name: image, widget: image, default: "/img/placeholder.png", required: false},
                {label: Alt image, image: alt, widget: string, required: false},
                {label: Banner title, name: title, widget: string},
                {label: Banner text, name: text, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link, name: link, widget: string},
              ],
            }
