backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      # HOME PAGE
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          # Main cover fields
          - {
              label: Main cover,
              name: mainCover,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # First sing-in row
          - {
              label: Sign in box,
              name: topSignIn,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # Partners section
          - {
              label: Partners section,
              name: partnersSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # School section
          - {
              label: School section,
              name: schoolSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
                {
                  label: Bullet,
                  name: bullet,
                  widget: list,
                  fields: [
                  {label: Heading, name: heading, widget: string},
                  {label: Subheading, name: subheading, widget: text},
                  {label: Call to action, name: cta, widget: markdown},
                  {label: Link, name: link, widget: string}
                  ],
                },
              ],
            }
          # Students sectioin
          - {
              label: Student section,
              name: studentsSection,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
                {
                  label: Bullet,
                  name: bullet,
                  widget: list,
                  fields: [
                    {label: Heading, name: heading, widget: string},
                    {label: Subheading, name: subheading, widget: text},
                    {label: Call to action, name: cta, widget: markdown},
                    {label: Link, name: link, widget: string}
                  ],
                },
              ],
            }
          # Second submission row
          - {
              label: Sign in box,
              name: bottomSignIn,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # Teachers section
          - {
              label: Teachers section,
              name: teachersSection,
              widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: text},
                {label: Call to action, name: cta, widget: string},
                {label: Link to, name: link, widget: string},
              ],
            }
          # News section
          - {
              label: News section,
              name: newsSection,
              widget: object,
              fields: [
                {label: Heading news, name: heading, widget: string},
                {label: Call to action, name: cta, widget: string},
                {label: Link to , name: link, widget: string},
              ],
            }

      # MASTER PAGE
      - file: "src/pages/master/index.md"
        label: "Master page"
        name: "master"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "master-page"}
          - {label: Title, name: title, widget: string}
          - {
              label: Paragraphs,
              name: paragraphs,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label:Description, name: description, widget: markdown}
              ],
            }
          - {label: Service title, name: serviceTitle, widget: string}
          - {
              label: Services,
              name: services,
              widget: list,
              fields: [
                {label: Image, name: image, widget: image, default: /img/service-placeholder.png},
                {label: "Alt image", name: alt, widget: string},
                {label: Heading, name: heading, widget: string},
                {label: Subheading, name: subheading, widget: string}
              ],
            }

      # PROGRAM PAGE
      - file: "src/pages/program/index.md"
        label: "Program page"
        name: "program"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "program-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: Title paragraphs, name: titleParagraphs, widget: string}
          - {
              label: Paragraphs,
              name: paragraphs,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown}
              ],
            }

      # STUDENTS PAGE
      - file: "src/pages/students/index.md"
        label: "Students page"
        name: "students"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "students-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {
              label: Projects,
              name: projects,
              widget: list,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown},
                {label: Image, name: image, widget: image},
                {label: Alt image, name: altImage, widget: string}
              ],
            }
          - {label: Students title, name: titleStudents, widget: string}
          - {
              label: Students,
              name: students,
              widget: list,
              fields: [
                {label: Full name, name: fullName, widget: string},
                {label: "Visible on homepage", name: main, widget: boolean},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Master, name: master, widget: number, default: 2010, valueType: int, min: 2010, max: 2030},
                {label: Company, name: company, widget: string},
                {label: Role, name: role, widget: string},
                {label: Description, name: description, widget: markdown}
              ],
            }

      # PARTNERS PAGE
      - file: "src/pages/partners/index.md"
        label: "Partners list"
        name: "partners"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "partners-page"}
          - {label: "Cover image", name: image, widget: image, default: /img/placeholder.png},
          - {label: "Alt image", name: altImage, widget: string},
          - {label: Title, name: title, widget: string},
          - {label: Description, name: description, widget: markdown},
          - {label: "Partners title", name: partnersTitle, widget: string},
          - {
              label: Partners,
              name: partners,
              widget: list,
              fields: [
                {label: Full name, name: name, widget: string},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Description, name: description, widget: markdown},
                {label: "Link", name: link, widget: string},
                {label: "Show in home", name: main, widget: boolean}
              ],
            }

      # TEACHERS PAGE
      - file: "src/pages/teachers/index.md"
        label: "Teachers list"
        name: "teachers"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "teachers-page"}
          - {label: "Cover image", name: image, widget: image, default: /img/placeholder.png}
          - {label: "Alt image", name: altImage, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - {label: "Teachers title", name: techersTitle, widget: string}
          - {
              label: Teachers,
              name: teachers,
              widget: list,
              fields: [
                {label: Full name, name: fullName, widget: string},
                {label: Image, name: image, widget: image, default: /img/student-img.png},
                {label: "Alt image", name: altImage, widget: string},
                {label: Link, name: link, widget: string},
                {label: Role, name: role, widget: string},
                {label: Biography, name: bio, widget: markdown}
              ],
            }

      # BANNERS
      - file: "src/pages/banners/index.md"
        label: "Banners list"
        name: "bannersList"
        fields:
          - {label: "Template key", name: "templateKey", widget: "hidden", default: "banners"}
          - {
              label: Banners,
              name: banners,
              widget: list,
              fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image, default: "/img/placeholder.png"},
                {label: Alt image, image: alt, widget: string},
                {label: Banner title, name: title, widget: string},
                {label: Banner text, name: text, widget: markdown},
                {label: Call to action, name: cta, widget: string},
                {label: Link, name: link, widget: string},
              ],
            }
